// Datos de ejemplo de las collabs: campañas, piezas con sus versiones y notas, y materiales. Todo
// inventado (el repo es público); las fotos son de Unsplash. Las fechas viven alrededor del 6 de
// octubre de 2026, el `HOY` de demo-data.ts.
import type { Collab, Material, Version } from "@/lib/influencer/modelo"
import { historialCollabs } from "@/lib/influencer/demo-historial"

const UNSPLASH = "https://images.unsplash.com"
const foto = (id: string, w = 800) => `${UNSPLASH}/photo-${id}?w=${w}&q=80&fit=crop`

const FOTOS = {
  lumea: "1570172619644-dfd03ed5d881",
  balsamo: "1556228720-195a672e8a03",
  botanica: "1596462502278-27bfdc403348",
  vero: "1583241800698-e8ab01830a07",
  veroTiktok: "1522335789203-aabd1fc54bc9",
  glow: "1487412947147-5cebf100ffc2",
  crema: "1599305090598-fe179d501227",
  gotero: "1617897903246-719242758050",
}

const lista = (items: string[]) => `<ul>${items.map((i) => `<li><p>${i}</p></li>`).join("")}</ul>`

/** El brief en un solo documento, con sus apartados de siempre. */
function brief(b: { objetivo: string; mensajes?: string[]; permitidos?: string[]; prohibidos?: string[]; hacer?: string[]; evitar?: string[] }) {
  const apartado = (titulo: string, items?: string[]) => (items?.length ? `<h3>${titulo}</h3>${lista(items)}` : "")
  return `<h3>Objetivo</h3><p>${b.objetivo}</p>${apartado("Mensajes clave", b.mensajes)}${apartado("Claims permitidos", b.permitidos)}${apartado("Claims prohibidos", b.prohibidos)}${apartado("Hay que", b.hacer)}${apartado("Evitar", b.evitar)}`
}

/** Un guion por apartados: título y párrafo. */
const guion = (apartados: [string, string][]) => apartados.map(([titulo, texto]) => `<h3>${titulo}</h3><p>${texto}</p>`).join("")

const GUION_LUMEA = guion([
  ["Gancho (0–3 s)", "«Esto es lo único que hago por la noche y mi piel nunca ha estado mejor.»"],
  ["Desarrollo (3–20 s)", "Me desmaquillo con el bálsamo, lo masajeo 30 segundos y lo retiro con agua tibia. Enseño la textura en la mano. Luego el sérum de noche: dos gotas, de dentro hacia fuera."],
  ["Mensajes de la marca", "Fórmula con retinal al 0,1 %, apta para pieles sensibles. Resultados visibles en 4 semanas (estudio clínico de la marca)."],
  ["Llamada a la acción", "«Tenéis un 15 % con el código MARTA15 en el enlace de mi bio.»"],
  ["Texto en pantalla", "«Rutina de noche en 3 pasos» · «Código MARTA15»"],
  ["Copy del post", "Mi rutina de noche de verdad, sin diez pasos. #publi @lumea.skin #rutinadenoche #skincare"],
  ["Notas de rodaje", "Luz cálida del baño, plano cenital para las texturas. Enseñar el envase entero al menos 2 segundos."],
])

const GUION_BOTANICA = guion([
  ["Gancho (0–3 s)", "«Llevo 15 días con este sérum de vitamina C y esto es lo que ha pasado.»"],
  ["Desarrollo (3–25 s)", "Primera impresión al abrirlo: color, textura y olor. Cómo lo aplico por la mañana antes del SPF. Qué he notado en la primera semana (luminosidad) y qué no (las manchas van a tardar más)."],
  ["Mensajes de la marca", "Vitamina C estabilizada al 15 %, sin perfume, envase de vidrio reciclable."],
  ["Llamada a la acción", "«El enlace está en mi bio; el reel de los resultados llega en dos semanas.»"],
  ["Copy del post", "Primera impresión del sérum de vitamina C de @botanicalab. En 15 días os cuento los resultados. #ad #vitaminac"],
])

const GUION_VERO = guion([
  ["Gancho (0–3 s)", "«Un look de otoño en 3 productos, y uno de ellos lo vais a querer.»"],
  ["Desarrollo (3–22 s)", "Base ligera, la paleta Terracota en los párpados (enseño los 4 tonos de cerca) y el labial Castaña. Antes y después."],
  ["Mensajes de la marca", "Paleta Terracota: 4 tonos mate y satinados, edición limitada de otoño."],
  ["Llamada a la acción", "«Todo en el enlace de mi bio.»"],
  ["Copy del post", "Mi look de otoño con la colección nueva de @maisonvero. #publi #lookdeotoño #maisonvero"],
])

const GUION_GLOW = guion([
  ["Gancho (0–3 s)", "«El SPF que por fin no me deja la cara blanca.»"],
  ["Desarrollo (3–18 s)", "Aplicación con los dos dedos de producto, cómo queda bajo el maquillaje, y el truco para reaplicar a mediodía."],
  ["Mensajes de la marca", "SPF 50+ de amplio espectro, acabado invisible, sin fragancia."],
  ["Llamada a la acción", "«Lanzamiento el 12 de octubre: enlace en la bio.»"],
  ["Copy del post", "Mi SPF de cada día, desde hoy a la venta. @glowstudio #publi #spf50 #glowstudio"],
])

const version = (v: Omit<Version, "notas" | "mensajes"> & Partial<Pick<Version, "notas" | "mensajes">>): Version => ({ notas: [], mensajes: [], ...v })

export const demoCollabs: Collab[] = [
  {
    id: "lumea",
    marcaId: "lumea",
    campana: "Rutina de noche",
    tipo: "directa",
    estado: "en-curso",
    importe: 1296,
    tint: "rose",
    coverUrl: foto(FOTOS.lumea),
    desde: "2026-10-01",
    hasta: "2026-10-20",
    brief: {
      texto: brief({
        objetivo: "Dar a conocer la rutina de noche de Lumea (bálsamo + sérum con retinal) entre mujeres de 25 a 40 años con piel sensible.",
        mensajes: ["Retinal al 0,1 % apto para pieles sensibles", "Resultados visibles en 4 semanas", "Rutina de 3 pasos, sin complicaciones"],
        permitidos: ["Apto para pieles sensibles", "Resultados visibles en 4 semanas (estudio clínico)"],
        prohibidos: ["Elimina las arrugas", "Efecto bótox", "Cura el acné"],
        hacer: ["Enseñar el envase entero al menos 2 segundos", "Mostrar la textura en la mano", "Marcar como publicidad en la propia plataforma"],
        evitar: ["Comparar con otras marcas", "Aplicarlo cerca de los ojos en cámara"],
      }),
      menciones: ["@lumea.skin"],
      hashtags: ["#publi", "#rutinadenoche", "#lumeaskin"],
      enlace: "https://example.com/rutina-de-noche",
      codigo: "MARTA15",
      exclusividad: "Skincare de noche · 2 meses",
      derechosUso: "Orgánico · 6 meses",
      rondasIncluidas: 2,
      producto: { estado: "recibido", detalle: "Bálsamo + sérum, recibidos el 3 de octubre" },
      contacto: { nombre: "Clara Benet", email: "clara@example.com" },
      condicionesPago: "30 días tras la publicación del reel",
    },
    piezas: [
      {
        id: "lumea-reel",
        collabId: "lumea",
        tipo: "video",
        formato: "reel",
        unidades: 1,
        titulo: "Reel · Mi rutina de noche",
        publicacion: "2026-10-15",
        estado: "borrador",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.lumea, 600),
        indicaciones: "Rutina completa en menos de 30 segundos, con el código en pantalla al final.",
        guion: [
          version({
            id: "lumea-reel-g1",
            tipo: "guion",
            numero: 1,
            estado: "aprobada",
            creadaEl: "2026-10-03T19:00:00",
            texto: GUION_LUMEA,
            enlace: { token: "rv-lumea-reel-g1", caduca: "2026-11-03" },
            notas: [
              {
                id: "n-lumea-1",
                autor: "Clara Benet",
                el: "2026-10-05T18:10:00",
                texto: "Perfecto. Solo una cosa: di «retinal», no «retinol», que es otro ingrediente.",
                ancla: { tipo: "texto", cita: "Fórmula con retinal al 0,1 %" },
                resuelta: true,
                respuestas: [{ id: "r-lumea-1", autor: "Marta", lado: "influencer", el: "2026-10-05T18:15:00", texto: "Cambiado, lo digo bien en el vídeo." }],
              },
            ],
            mensajes: [{ id: "m-lumea-1", autor: "Marta", lado: "influencer", el: "2026-10-03T19:05:00", texto: "Te paso el guion del reel. Si algo no encaja con el brief, márcalo sobre el texto." }],
            aprobada: { por: "Clara Benet", el: "2026-10-05T18:20:00" },
          }),
        ],
        media: [],
      },
      {
        id: "lumea-stories",
        collabId: "lumea",
        tipo: "video",
        formato: "story",
        unidades: 3,
        titulo: "3 stories · Antes y después",
        publicacion: "2026-10-18",
        estado: "borrador",
        rondaActual: 1,
        guion: [
          version({
            id: "lumea-stories-g1",
            tipo: "guion",
            numero: 1,
            estado: "borrador",
            creadaEl: "2026-10-05T22:00:00",
            texto: guion([
              ["Story 1", "El paquete abierto, qué lleva y por qué lo he elegido."],
              ["Story 2", "Textura del sérum en la mano y cómo lo aplico (sticker de enlace)."],
              ["Story 3", "Piel por la mañana + código MARTA15 en grande. #publi @lumea.skin"],
            ]),
          }),
        ],
        media: [],
      },
      {
        id: "lumea-foto",
        collabId: "lumea",
        tipo: "foto",
        red: "instagram",
        unidades: 1,
        titulo: "Foto · El sérum en el baño",
        publicacion: "2026-10-20",
        estado: "en-revision",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.balsamo, 600),
        indicaciones: "Foto de producto para el post del último día, con luz natural.",
        guion: [],
        media: [
          version({
            id: "lumea-foto-m1",
            tipo: "media",
            numero: 1,
            estado: "en-revision",
            creadaEl: "2026-10-05T12:00:00",
            archivos: [{ nombre: "lumea-serum-bano-v1.jpg", tamano: 3_400_000, url: foto(FOTOS.balsamo, 1200) }],
            copy: "El paso que no me salto ninguna noche. @lumea.skin #publi #rutinadenoche #lumeaskin",
            enlace: { token: "rv-lumea-foto-m1", caduca: "2026-11-04" },
            mensajes: [{ id: "m-lumea-2", autor: "Marta", lado: "influencer", el: "2026-10-05T12:02:00", texto: "Te paso la foto del post. ¿Te encaja el encuadre?" }],
            notas: [{ id: "n-lumea-2", autor: "Clara Benet", el: "2026-10-06T09:20:00", texto: "¿Se puede ver un poco más el nombre del sérum en el envase?", ancla: { tipo: "punto", x: 58, y: 46, imagen: 0 }, resuelta: false, respuestas: [] }],
          }),
        ],
      },
    ],
    cobro: { estado: "por-facturar" },
    plazos: [{ id: "lumea-p1", concepto: "A 30 días tras publicar", porcentaje: 100 }],
    facturacion: { razonSocial: "Lumea Cosmetics S.L.", nif: "B00000001", direccion: "Calle Ejemplo 12, 46001 Valencia", email: "facturas@example.com", pedido: "PO-2026-118" },
    propuestaId: "p-lumea",
    creadaEl: "2026-09-18T12:00:00",
  },
  {
    id: "botanica",
    marcaId: "botanica",
    campana: "Sérum de vitamina C",
    tipo: "red",
    estado: "en-curso",
    importe: 1900,
    importeNeto: 1520,
    tint: "mint",
    coverUrl: foto(FOTOS.botanica),
    desde: "2026-10-05",
    hasta: "2026-11-05",
    brief: {
      texto: brief({
        objetivo: "Dos reels que enseñen la experiencia real con el sérum: la primera impresión y los resultados a los 15 días.",
        mensajes: ["Vitamina C estabilizada al 15 %", "Sin perfume", "Envase de vidrio reciclable"],
        permitidos: ["Más luminosidad desde la primera semana", "Fórmula estabilizada"],
        prohibidos: ["Quita las manchas", "Sustituye al SPF"],
        hacer: ["Grabar el segundo reel con el mismo encuadre que el primero", "Decir el porcentaje de vitamina C"],
        evitar: ["Mezclarlo en cámara con otros ácidos"],
      }),
      menciones: ["@botanicalab"],
      hashtags: ["#publi", "#vitaminac", "#botanicalab"],
      enlace: "https://example.com/vitamina-c",
      derechosUso: "Orgánico · 3 meses",
      rondasIncluidas: 2,
      producto: { estado: "enviado", detalle: "Sale el 6 de octubre; llega en 48 h" },
      contacto: { nombre: "Pau Ribes", email: "pau@example.com" },
      condicionesPago: "Factura Astratic; cobro a 30 días tras el segundo reel",
    },
    piezas: [
      {
        id: "botanica-reel-1",
        collabId: "botanica",
        tipo: "video",
        formato: "reel",
        unidades: 1,
        titulo: "Reel 1 · Primera impresión",
        publicacion: "2026-10-22",
        estado: "borrador",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.botanica, 600),
        guion: [version({ id: "botanica-reel-1-g1", tipo: "guion", numero: 1, estado: "borrador", creadaEl: "2026-10-05T23:10:00", texto: GUION_BOTANICA })],
        media: [],
      },
      {
        id: "botanica-reel-2",
        collabId: "botanica",
        tipo: "video",
        formato: "reel",
        unidades: 1,
        titulo: "Reel 2 · Resultados a los 15 días",
        publicacion: "2026-11-05",
        estado: "borrador",
        rondaActual: 1,
        indicaciones: "Mismo encuadre que el reel 1 para que se vea el antes y el después.",
        guion: [],
        media: [],
      },
    ],
    cobro: { estado: "por-facturar" },
    plazos: [{ id: "botanica-p1", concepto: "Al publicar el segundo reel", porcentaje: 100 }],
    creadaEl: "2026-09-28T10:00:00",
  },
  {
    id: "vero",
    marcaId: "vero",
    campana: "Colección otoño",
    tipo: "directa",
    estado: "en-curso",
    importe: 1650,
    tint: "peach",
    coverUrl: foto(FOTOS.vero),
    desde: "2026-09-20",
    hasta: "2026-10-20",
    brief: {
      texto: brief({
        objetivo: "Presentar la colección de otoño (paleta Terracota y labial Castaña) con un look completo y un tutorial corto.",
        mensajes: ["Edición limitada de otoño", "4 tonos mate y satinados", "Larga duración sin retoques"],
        permitidos: ["Larga duración", "Pigmentación alta"],
        prohibidos: ["Hipoalergénico", "No testado en animales (sin certificado)"],
        hacer: ["Enseñar los 4 tonos de cerca", "Nombrar la paleta en pantalla"],
        evitar: ["Mezclar con productos de otras marcas en el mismo plano"],
      }),
      menciones: ["@maisonvero"],
      hashtags: ["#publi", "#lookdeotoño", "#maisonvero"],
      enlace: "https://example.com/otono",
      exclusividad: "Maquillaje de ojos · 1 mes",
      derechosUso: "Paid · 3 meses",
      rondasIncluidas: 2,
      producto: { estado: "recibido" },
      contacto: { nombre: "Inés Roldán", email: "ines@example.com" },
      condicionesPago: "50 % al aprobar el guion, 50 % a 30 días tras publicar",
    },
    piezas: [
      {
        id: "vero-reel",
        collabId: "vero",
        tipo: "video",
        formato: "reel",
        unidades: 1,
        titulo: "Reel · Look de otoño",
        publicacion: "2026-10-15",
        estado: "cambios",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.vero, 600),
        guion: [
          version({ id: "vero-reel-g1", tipo: "guion", numero: 1, estado: "aprobada", creadaEl: "2026-09-26T18:00:00", texto: GUION_VERO, enlace: { token: "rv-vero-reel-g1", caduca: "2026-10-26" }, aprobada: { por: "Inés Roldán", el: "2026-09-28T10:30:00" } }),
        ],
        media: [
          version({
            id: "vero-reel-m1",
            tipo: "media",
            numero: 1,
            estado: "cambios",
            creadaEl: "2026-10-02T17:40:00",
            archivos: [{ nombre: "vero-look-otono-v1.mp4", tamano: 148_000_000, duracion: 27, url: foto(FOTOS.vero, 600) }],
            copy: "Mi look de otoño con la colección nueva de @maisonvero. #publi #lookdeotoño #maisonvero",
            enlace: { token: "rv-vero-reel-m1", caduca: "2026-11-02" },
            mensajes: [
              { id: "m-vero-1", autor: "Marta", lado: "influencer", el: "2026-10-02T17:42:00", texto: "Aquí tienes la v1 del reel. Lo que veas, márcalo sobre el vídeo." },
              { id: "m-vero-2", autor: "Inés Roldán", lado: "marca", el: "2026-10-06T10:16:00", texto: "Te he dejado dos notas. Lo demás, genial." },
            ],
            notas: [
              { id: "n-vero-1", autor: "Inés Roldán", el: "2026-10-06T10:12:00", texto: "El producto se ve poco en el primer plano. ¿Puedes acercar la paleta a cámara un segundo más?", ancla: { tipo: "segundo", segundo: 4 }, resuelta: false, respuestas: [] },
              { id: "n-vero-2", autor: "Inés Roldán", el: "2026-10-06T10:15:00", texto: "Añade el nombre «Terracota» en pantalla cuando enseñas los tonos.", ancla: { tipo: "segundo", segundo: 18 }, resuelta: false, respuestas: [] },
            ],
          }),
        ],
      },
      {
        id: "vero-tiktok",
        collabId: "vero",
        tipo: "video",
        formato: "tiktok",
        unidades: 1,
        titulo: "TikTok · Tutorial en 30 segundos",
        publicacion: "2026-10-02",
        estado: "publicado",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.veroTiktok, 600),
        guion: [],
        media: [
          version({ id: "vero-tiktok-m1", tipo: "media", numero: 1, estado: "aprobada", creadaEl: "2026-09-29T12:00:00", archivos: [{ nombre: "vero-tutorial-v1.mp4", tamano: 96_000_000, duracion: 31, url: foto(FOTOS.veroTiktok, 600) }], aprobada: { por: "Inés Roldán", el: "2026-09-30T09:45:00" } }),
        ],
        publicada: { url: "https://tiktok.com", fecha: "2026-10-02", marcadaPubli: true },
      },
    ],
    cobro: { estado: "facturado", vencimiento: "2026-10-30", factura: "2026-017" },
    plazos: [
      { id: "vero-p1", concepto: "Al aprobar el guion", porcentaje: 50 },
      { id: "vero-p2", concepto: "A 30 días tras publicar", porcentaje: 50 },
    ],
    facturacion: { razonSocial: "Maison Vero Beauty S.L.", nif: "B00000002", direccion: "Calle Ejemplo 5, 08001 Barcelona", email: "administracion@example.com" },
    creadaEl: "2026-09-15T10:00:00",
  },
  {
    id: "glow",
    marcaId: "glow",
    campana: "Lanzamiento SPF",
    tipo: "red",
    estado: "en-curso",
    importe: 980,
    importeNeto: 784,
    tint: "lavender",
    coverUrl: foto(FOTOS.glow),
    desde: "2026-10-01",
    hasta: "2026-10-12",
    brief: {
      texto: brief({
        objetivo: "Acompañar el lanzamiento del SPF 50+ invisible el 12 de octubre con un reel de uso diario y un carrusel con tres tonos de piel.",
        mensajes: ["SPF 50+ de amplio espectro", "Acabado invisible", "Sin fragancia"],
        permitidos: ["Protección muy alta", "Acabado invisible en todos los tonos de piel"],
        prohibidos: ["Protección total", "Bloqueador"],
        hacer: ["Publicar el 12 de octubre entre las 18 y las 20 h"],
        evitar: ["Enseñar el producto antes del día del lanzamiento"],
      }),
      menciones: ["@glowstudio"],
      hashtags: ["#publi", "#spf50", "#glowstudio"],
      enlace: "https://example.com/spf",
      derechosUso: "Orgánico · 3 meses",
      rondasIncluidas: 1,
      producto: { estado: "recibido" },
      contacto: { nombre: "Marc Soler", email: "marc@example.com" },
      condicionesPago: "Factura Astratic; cobro a 30 días",
    },
    piezas: [
      {
        id: "glow-reel",
        collabId: "glow",
        tipo: "video",
        formato: "reel",
        unidades: 1,
        titulo: "Reel · SPF cada día",
        publicacion: "2026-10-12",
        estado: "programado",
        rondaActual: 2,
        portadaUrl: foto(FOTOS.glow, 600),
        guion: [version({ id: "glow-reel-g1", tipo: "guion", numero: 1, estado: "aprobada", creadaEl: "2026-09-27T10:00:00", texto: GUION_GLOW, aprobada: { por: "Marc Soler", el: "2026-09-29T11:00:00" } })],
        media: [
          version({
            id: "glow-reel-m1",
            tipo: "media",
            numero: 1,
            estado: "cambios",
            creadaEl: "2026-10-01T16:00:00",
            archivos: [{ nombre: "glow-spf-v1.mp4", tamano: 121_000_000, duracion: 22, url: foto(FOTOS.glow, 600) }],
            notas: [{ id: "n-glow-1", autor: "Marc Soler", el: "2026-10-02T09:30:00", texto: "Quita el plano del envase antiguo: en el lanzamiento va el nuevo.", ancla: { tipo: "segundo", segundo: 9 }, resuelta: true, respuestas: [{ id: "r-glow-1", autor: "Marta", lado: "influencer", el: "2026-10-02T10:00:00", texto: "Hecho en la v2." }] }],
          }),
          version({ id: "glow-reel-m2", tipo: "media", numero: 2, estado: "aprobada", creadaEl: "2026-10-03T18:30:00", archivos: [{ nombre: "glow-spf-v2.mp4", tamano: 119_000_000, duracion: 22, url: foto(FOTOS.glow, 600) }], copy: "Mi SPF de cada día, desde hoy a la venta. @glowstudio #publi #spf50 #glowstudio", enlace: { token: "rv-glow-reel-m2", caduca: "2026-11-03" }, aprobada: { por: "Marc Soler", el: "2026-10-04T12:10:00" } }),
        ],
      },
      {
        id: "glow-carrusel",
        collabId: "glow",
        tipo: "carrusel",
        red: "instagram",
        unidades: 1,
        titulo: "Carrusel · Tres tonos de piel",
        publicacion: "2026-10-12",
        estado: "en-revision",
        rondaActual: 1,
        portadaUrl: foto(FOTOS.crema, 600),
        indicaciones: "Tres fotos: textura, aplicación y acabado, con luz natural.",
        guion: [],
        media: [
          version({
            id: "glow-carrusel-m1",
            tipo: "media",
            numero: 1,
            estado: "en-revision",
            creadaEl: "2026-10-05T16:20:00",
            archivos: [
              { nombre: "glow-carrusel-1-textura.jpg", tamano: 2_900_000, url: foto(FOTOS.crema, 1200) },
              { nombre: "glow-carrusel-2-aplicacion.jpg", tamano: 3_100_000, url: foto(FOTOS.gotero, 1200) },
              { nombre: "glow-carrusel-3-acabado.jpg", tamano: 2_700_000, url: foto(FOTOS.glow, 1200) },
            ],
            copy: "Tres tonos de piel, un mismo SPF invisible. @glowstudio #publi #spf50",
            enlace: { token: "rv-glow-carrusel-m1", caduca: "2026-11-04" },
            mensajes: [{ id: "m-glow-1", autor: "Marta", lado: "influencer", el: "2026-10-05T16:22:00", texto: "Aquí van las tres fotos del carrusel, en el orden en que se publican." }],
            notas: [{ id: "n-glow-2", autor: "Marc Soler", el: "2026-10-06T08:50:00", texto: "En la segunda foto el tono queda algo frío. ¿Lo calentamos un poco?", ancla: { tipo: "punto", x: 42, y: 55, imagen: 1 }, resuelta: false, respuestas: [] }],
          }),
        ],
      },
    ],
    cobro: { estado: "por-facturar" },
    plazos: [{ id: "glow-p1", concepto: "A 30 días tras publicar", porcentaje: 100 }],
    creadaEl: "2026-09-24T10:00:00",
  },
  {
    id: "mirra",
    marcaId: "mirra",
    campana: "Perfume de invierno",
    tipo: "directa",
    estado: "por-empezar",
    importe: 800,
    tint: "peach",
    desde: "2026-11-15",
    hasta: "2026-12-10",
    brief: { texto: "", menciones: [], hashtags: [], rondasIncluidas: 2, contacto: { nombre: "Teo Valls", email: "teo@example.com" }, condicionesPago: "30 días tras publicar" },
    piezas: [],
    cobro: { estado: "por-facturar" },
    plazos: [{ id: "mirra-p1", concepto: "A 30 días tras publicar", porcentaje: 100 }],
    creadaEl: "2026-10-04T10:00:00",
  },
  {
    id: "botanica-verano",
    marcaId: "botanica",
    campana: "Sérum de verano",
    tipo: "red",
    estado: "por-cobrar",
    importe: 950,
    importeNeto: 760,
    tint: "mint",
    desde: "2026-07-01",
    hasta: "2026-07-20",
    brief: { texto: brief({ objetivo: "Un reel de rutina de verano con el sérum hidratante.", mensajes: ["Hidratación ligera para el verano"] }), menciones: ["@botanicalab"], hashtags: ["#publi"], rondasIncluidas: 2, contacto: { nombre: "Pau Ribes", email: "pau@example.com" }, condicionesPago: "30 días" },
    piezas: [
      { id: "botanica-verano-reel", collabId: "botanica-verano", tipo: "video", formato: "reel", unidades: 1, titulo: "Reel · Rutina de verano", publicacion: "2026-07-18", estado: "resultados", rondaActual: 1, guion: [], media: [], publicada: { url: "https://instagram.com", fecha: "2026-07-18", marcadaPubli: true } },
    ],
    cobro: { estado: "vencido", vencimiento: "2026-09-30", factura: "2026-014" },
    plazos: [{ id: "botanica-verano-p1", concepto: "A 30 días", porcentaje: 100 }],
    creadaEl: "2026-06-20T10:00:00",
  },
  {
    id: "lumea-verano",
    marcaId: "lumea",
    campana: "Protección solar facial",
    tipo: "directa",
    estado: "cerrada",
    importe: 1150,
    tint: "rose",
    desde: "2026-06-01",
    hasta: "2026-06-20",
    brief: { texto: brief({ objetivo: "Reel y stories del SPF facial." }), menciones: ["@lumea.skin"], hashtags: ["#publi"], rondasIncluidas: 2, contacto: { nombre: "Clara Benet", email: "clara@example.com" }, condicionesPago: "30 días" },
    piezas: [
      { id: "lumea-verano-reel", collabId: "lumea-verano", tipo: "video", formato: "reel", unidades: 1, titulo: "Reel · SPF facial", publicacion: "2026-06-15", estado: "resultados", rondaActual: 1, guion: [], media: [], publicada: { url: "https://instagram.com", fecha: "2026-06-15", marcadaPubli: true } },
      { id: "lumea-verano-stories", collabId: "lumea-verano", tipo: "video", formato: "story", unidades: 2, titulo: "2 stories · Reaplicar", publicacion: "2026-06-18", estado: "resultados", rondaActual: 1, guion: [], media: [], publicada: { url: "https://instagram.com", fecha: "2026-06-18", marcadaPubli: true } },
    ],
    cobro: { estado: "cobrado", vencimiento: "2026-07-15", factura: "2026-009" },
    plazos: [{ id: "lumea-verano-p1", concepto: "A 30 días", porcentaje: 100 }],
    facturacion: { razonSocial: "Lumea Cosmetics S.L.", nif: "B00000001", direccion: "Calle Ejemplo 12, 46001 Valencia", email: "facturas@example.com" },
    creadaEl: "2026-05-12T10:00:00",
  },
  {
    id: "vero-primavera",
    marcaId: "vero",
    campana: "Colección primavera",
    tipo: "directa",
    estado: "cerrada",
    importe: 1400,
    tint: "peach",
    desde: "2026-04-01",
    hasta: "2026-04-20",
    brief: { texto: brief({ objetivo: "Look de primavera con la colección nueva." }), menciones: ["@maisonvero"], hashtags: ["#publi"], rondasIncluidas: 2, contacto: { nombre: "Inés Roldán", email: "ines@example.com" }, condicionesPago: "30 días" },
    piezas: [
      { id: "vero-primavera-reel", collabId: "vero-primavera", tipo: "video", formato: "reel", unidades: 1, titulo: "Reel · Look de primavera", publicacion: "2026-04-14", estado: "resultados", rondaActual: 2, guion: [], media: [], publicada: { url: "https://instagram.com", fecha: "2026-04-14", marcadaPubli: true } },
    ],
    cobro: { estado: "cobrado", vencimiento: "2026-05-14", factura: "2026-006" },
    plazos: [{ id: "vero-primavera-p1", concepto: "A 30 días", porcentaje: 100 }],
    facturacion: { razonSocial: "Maison Vero Beauty S.L.", nif: "B00000002", direccion: "Calle Ejemplo 5, 08001 Barcelona", email: "administracion@example.com" },
    creadaEl: "2026-03-10T10:00:00",
  },
  ...historialCollabs,
]

export const demoMateriales: Material[] = [
  { id: "m-lumea-brief", collabId: "lumea", nombre: "Brief Rutina de noche.pdf", tipo: "pdf", origen: "marca", tamano: 2_400_000, url: "#", subidoEl: "2026-09-18T12:30:00", descripcion: "El brief completo de la marca" },
  { id: "m-lumea-logos", collabId: "lumea", nombre: "Logos Lumea.zip", tipo: "zip", origen: "marca", tamano: 8_100_000, url: "#", subidoEl: "2026-09-18T12:30:00" },
  { id: "m-lumea-producto-1", collabId: "lumea", nombre: "Sérum de noche · packshot.jpg", tipo: "imagen", origen: "marca", tamano: 1_900_000, url: "#", previewUrl: foto(FOTOS.lumea, 400), subidoEl: "2026-09-19T09:00:00" },
  { id: "m-lumea-producto-2", collabId: "lumea", nombre: "Bálsamo · textura.jpg", tipo: "imagen", origen: "marca", tamano: 2_200_000, url: "#", previewUrl: foto(FOTOS.balsamo, 400), subidoEl: "2026-09-19T09:00:00" },
  { id: "m-lumea-claims", collabId: "lumea", nombre: "Guía de claims y menciones.pdf", tipo: "pdf", origen: "marca", tamano: 640_000, url: "#", subidoEl: "2026-09-19T09:05:00" },
  { id: "m-lumea-landing", collabId: "lumea", nombre: "Landing de la campaña", tipo: "enlace", origen: "marca", url: "https://example.com/rutina-de-noche", subidoEl: "2026-09-19T09:05:00" },
  { id: "m-lumea-contrato", collabId: "lumea", nombre: "Contrato firmado.pdf", tipo: "pdf", origen: "mia", tamano: 310_000, url: "#", subidoEl: "2026-09-22T17:00:00" },
  { id: "m-vero-brief", collabId: "vero", nombre: "Brief Colección otoño.pdf", tipo: "pdf", origen: "marca", tamano: 3_100_000, url: "#", subidoEl: "2026-09-15T11:00:00" },
  { id: "m-vero-paleta", collabId: "vero", nombre: "Paleta Terracota · packshot.jpg", tipo: "imagen", origen: "marca", tamano: 2_700_000, url: "#", previewUrl: foto(FOTOS.vero, 400), subidoEl: "2026-09-15T11:00:00" },
  { id: "m-vero-referencias", collabId: "vero", nombre: "Referencias de la marca", tipo: "enlace", origen: "marca", url: "https://example.com/referencias", subidoEl: "2026-09-15T11:05:00", descripcion: "Looks que les gustan, para el tono" },
  { id: "m-vero-contrato", collabId: "vero", nombre: "Contrato firmado.pdf", tipo: "pdf", origen: "mia", tamano: 290_000, url: "#", subidoEl: "2026-09-17T10:00:00" },
  { id: "m-botanica-brief", collabId: "botanica", nombre: "Brief Sérum de vitamina C.pdf", tipo: "pdf", origen: "marca", tamano: 1_800_000, url: "#", subidoEl: "2026-09-28T10:30:00" },
  { id: "m-botanica-producto", collabId: "botanica", nombre: "Sérum · packshot.jpg", tipo: "imagen", origen: "marca", tamano: 2_000_000, url: "#", previewUrl: foto(FOTOS.botanica, 400), subidoEl: "2026-09-28T10:30:00" },
  { id: "m-glow-brief", collabId: "glow", nombre: "Brief Lanzamiento SPF.pdf", tipo: "pdf", origen: "marca", tamano: 1_200_000, url: "#", subidoEl: "2026-09-24T10:30:00" },
  { id: "m-glow-logo", collabId: "glow", nombre: "Logo Glow Studio.zip", tipo: "zip", origen: "marca", tamano: 4_400_000, url: "#", subidoEl: "2026-09-24T10:30:00" },
]
