// Datos de ejemplo de Contenidos: el directorio de ideas y documentos de la creadora inventada, sus
// pilares, sus contenidos propios de octubre, las plantillas de guion para lo que publica por su
// cuenta y las fechas clave que escribe Astratic. Nada real: el repo es público.
import type { Apunte, Carpeta, Contenido, FechaClave, Pilar, PlantillaGuion, VinculoApunte } from "@/lib/influencer/modelo"

const UNSPLASH = "https://images.unsplash.com"
const foto = (id: string, w = 600) => `${UNSPLASH}/photo-${id}?w=${w}&q=80&fit=crop`

const FOTOS = {
  crema: "1599305090598-fe179d501227",
  gotero: "1617897903246-719242758050",
  balsamo: "1556228720-195a672e8a03",
  pinceles: "1522335789203-aabd1fc54bc9",
  lumea: "1570172619644-dfd03ed5d881",
  glow: "1487412947147-5cebf100ffc2",
}

const lista = (items: string[]) => `<ul>${items.map((i) => `<li><p>${i}</p></li>`).join("")}</ul>`
const apartados = (partes: [string, string][]) => partes.map(([titulo, texto]) => `<h3>${titulo}</h3><p>${texto}</p>`).join("")

export const demoPilares: Pilar[] = [
  { id: "p-rutinas", nombre: "Rutinas", tint: "lavender" },
  { id: "p-reviews", nombre: "Reviews", tint: "peach" },
  { id: "p-consejos", nombre: "Consejos", tint: "mint" },
  { id: "p-dia", nombre: "Mi día a día", tint: "sky" },
]

export const demoCarpetas: Carpeta[] = [
  { id: "k-ganchos", nombre: "Ganchos", tint: "lavender" },
  { id: "k-tendencias", nombre: "Tendencias", tint: "rose" },
  { id: "k-probar", nombre: "Productos por probar", tint: "mint" },
  { id: "k-campanas", nombre: "Campañas del año", tint: "peach" },
  { id: "k-halloween", nombre: "Halloween", tint: "lavender", padreId: "k-campanas" },
  { id: "k-black-friday", nombre: "Black Friday", tint: "sky", padreId: "k-campanas" },
  { id: "k-navidad", nombre: "Navidad", tint: "rose", padreId: "k-campanas" },
  { id: "k-metodo", nombre: "Cómo trabajo", tint: "lime" },
]

export const demoFechasClave: FechaClave[] = [
  { id: "salud-mental", nombre: "Día Mundial de la Salud Mental", fecha: "2026-10-10", descripcion: "Autocuidado y rutinas que calman" },
  { id: "cancer-mama", nombre: "Día contra el Cáncer de Mama", fecha: "2026-10-19", descripcion: "Muchas marcas de belleza sacan ediciones rosas" },
  { id: "halloween", nombre: "Halloween", fecha: "2026-10-31", descripcion: "Maquillaje y looks rápidos" },
  { id: "singles-day", nombre: "Singles Day", fecha: "2026-11-11", descripcion: "Descuentos online del 11 del 11" },
  { id: "black-friday", nombre: "Black Friday", fecha: "2026-11-27", descripcion: "Las marcas cierran sus campañas con semanas de margen" },
  { id: "cyber-monday", nombre: "Cyber Monday", fecha: "2026-11-30" },
  { id: "navidad", nombre: "Navidad", fecha: "2026-12-25", descripcion: "Regalos, packs y looks de fiesta" },
  { id: "nochevieja", nombre: "Nochevieja", fecha: "2026-12-31", descripcion: "Looks de fiesta" },
  { id: "reyes", nombre: "Reyes", fecha: "2027-01-06" },
  { id: "rebajas", nombre: "Rebajas de invierno", fecha: "2027-01-07", descripcion: "Empiezan en muchas tiendas" },
  { id: "san-valentin", nombre: "San Valentín", fecha: "2027-02-14" },
  { id: "dia-mujer", nombre: "Día de la Mujer", fecha: "2027-03-08" },
  { id: "dia-padre", nombre: "Día del Padre", fecha: "2027-03-19" },
  { id: "dia-madre", nombre: "Día de la Madre", fecha: "2027-05-02", descripcion: "Primer domingo de mayo: de las fechas fuertes de la belleza" },
]

export const demoPlantillasGuionPropias: PlantillaGuion[] = [
  {
    id: "pg-gancho-valor",
    nombre: "Gancho, valor y llamada a la acción",
    descripcion: "La de siempre para un reel o un TikTok corto",
    texto: apartados([
      ["Gancho (0–3 s)", "La frase o la imagen que para el scroll."],
      ["Valor", "Lo que se lleva quien lo ve: el truco, el paso, la opinión."],
      ["Llamada a la acción", "Guardar, comentar o seguirte para la parte 2."],
      ["Texto en pantalla", "Los rótulos, en orden."],
    ]),
  },
  {
    id: "pg-tutorial",
    nombre: "Tutorial paso a paso",
    descripcion: "Para enseñar a hacer algo en tres o cuatro pasos",
    texto: apartados([
      ["Gancho (0–3 s)", "El resultado primero."],
      ["Paso 1", "Qué haces y con qué producto."],
      ["Paso 2", "El truco que nadie cuenta."],
      ["Paso 3", "Cómo queda."],
      ["Llamada a la acción", "Guárdalo para cuando lo pruebes."],
    ]),
  },
  {
    id: "pg-antes-despues",
    nombre: "Antes y después",
    descripcion: "Un cambio que se ve, con lo que hiciste entre medias",
    texto: apartados([
      ["Gancho (0–3 s)", "El después, sin explicar nada."],
      ["El antes", "Cómo estaba y qué te preocupaba."],
      ["Qué hice", "Productos, tiempo y constancia."],
      ["El después", "El resultado, con la misma luz."],
      ["Lo que aprendí", "Lo que le dirías a quien empieza."],
    ]),
  },
  {
    id: "pg-review",
    nombre: "Review sincera",
    descripcion: "Un producto con lo bueno y lo que no",
    texto: apartados([
      ["Gancho (0–3 s)", "Tu veredicto en una frase."],
      ["Qué es y cuánto cuesta", "Para quién es y dónde se compra."],
      ["Lo bueno", "Textura, resultado y duración."],
      ["Lo que no", "Lo que cambiarías."],
      ["¿Lo recomiendo?", "Sí, no o depende de tu piel."],
      ["Publicidad", "Si te lo han regalado, dilo y marca #publi."],
    ]),
  },
  {
    id: "pg-grwm",
    nombre: "Prepárate conmigo (GRWM)",
    descripcion: "Te maquillas mientras cuentas algo",
    texto: apartados([
      ["Gancho (0–3 s)", "A dónde vas o qué te ha pasado."],
      ["La charla", "El tema del día, mientras te maquillas."],
      ["Los productos", "Cada uno en su plano, con su nombre en pantalla."],
      ["El resultado", "El look terminado."],
    ]),
  },
]

const creado = (dia: string) => `${dia}T10:00:00`

export const demoApuntes: Apunte[] = [
  {
    id: "a-rutina-noche",
    tipo: "idea",
    titulo: "Rutina de noche en 30 segundos",
    texto: "<p>Todo en un plano cenital, cortes rápidos al ritmo del audio. La clave: que se vea la textura del bálsamo.</p>",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-rutinas",
    formato: "reel",
    redes: ["instagram", "tiktok"],
    referencias: [{ id: "r1", tipo: "imagen", url: foto(FOTOS.balsamo), titulo: "La luz que quiero" }],
    portadaUrl: foto(FOTOS.balsamo),
    creadoEl: creado("2026-09-28"),
    actualizadoEl: creado("2026-10-01"),
  },
  {
    id: "a-colorete-viral",
    tipo: "idea",
    titulo: "Probando el truco viral del colorete",
    texto: "<p>El truco de poner el colorete antes de la base. ¿Funciona en piel grasa?</p>",
    carpetaId: "k-tendencias",
    favorito: true,
    estado: "para-hacer",
    pilarId: "p-reviews",
    formato: "reel",
    redes: ["instagram"],
    referencias: [{ id: "r2", tipo: "enlace", url: "https://www.tiktok.com/@ejemplo/video/7400000000000000001", titulo: "TikTok" }],
    caducaEl: "2026-10-12",
    creadoEl: creado("2026-10-02"),
    actualizadoEl: creado("2026-10-03"),
  },
  {
    id: "a-dupes-serums",
    tipo: "idea",
    titulo: "Dupes de sérums caros",
    texto: "<p>Tres sérums de farmacia que hacen lo mismo que los de 80 €. Comparar ingredientes en pantalla.</p>",
    carpetaId: "k-probar",
    favorito: true,
    estado: "para-hacer",
    pilarId: "p-reviews",
    formato: "reel",
    redes: ["instagram", "tiktok"],
    referencias: [{ id: "r3", tipo: "imagen", url: foto(FOTOS.gotero) }],
    portadaUrl: foto(FOTOS.gotero),
    creadoEl: creado("2026-09-20"),
    actualizadoEl: creado("2026-10-04"),
  },
  {
    id: "a-black-friday",
    tipo: "idea",
    titulo: "Top 5 de belleza para Black Friday",
    texto: "<p>Lo que sí merece la pena comprar con descuento y lo que no. Prepararla a principios de noviembre.</p>",
    carpetaId: "k-black-friday",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-reviews",
    formato: "reel",
    redes: ["instagram"],
    referencias: [{ id: "r4", tipo: "imagen", url: foto(FOTOS.crema) }],
    portadaUrl: foto(FOTOS.crema),
    fechaClaveId: "black-friday",
    creadoEl: creado("2026-10-01"),
    actualizadoEl: creado("2026-10-01"),
  },
  {
    id: "a-adviento",
    tipo: "idea",
    titulo: "Calendario de adviento de belleza: ¿vale la pena?",
    texto: "<p>Abrirlo entero y sumar lo que cuesta cada producto por separado.</p>",
    carpetaId: "k-navidad",
    favorito: false,
    estado: "apuntada",
    formato: "tiktok",
    redes: ["tiktok"],
    referencias: [],
    fechaClaveId: "navidad",
    creadoEl: creado("2026-10-05"),
    actualizadoEl: creado("2026-10-05"),
  },
  {
    id: "a-audio-grwm",
    tipo: "idea",
    titulo: "Audio de GRWM que está en todas partes",
    texto: "",
    carpetaId: "k-tendencias",
    favorito: false,
    estado: "apuntada",
    formato: "reel",
    redes: ["instagram"],
    referencias: [{ id: "r5", tipo: "enlace", url: "https://www.instagram.com/reel/EJEMPLO123/", titulo: "Instagram" }],
    caducaEl: "2026-10-08",
    creadoEl: creado("2026-10-05"),
    actualizadoEl: creado("2026-10-05"),
  },
  {
    id: "a-protector-maquillaje",
    tipo: "idea",
    titulo: "¿Qué protector uso debajo del maquillaje?",
    texto: "<p>Me lo habéis preguntado doce veces esta semana. Responder al comentario con vídeo.</p>",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-consejos",
    formato: "tiktok",
    redes: ["tiktok"],
    referencias: [],
    creadoEl: creado("2026-10-04"),
    actualizadoEl: creado("2026-10-04"),
  },
  {
    id: "a-botanica",
    tipo: "idea",
    titulo: "Rutina de otoño con Botánica Lab",
    texto: "<p>Para proponérsela: ya trabajamos en verano y les fue bien. Tres productos de su línea nueva.</p>",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-rutinas",
    formato: "reel",
    redes: ["instagram"],
    referencias: [],
    marcaId: "botanica",
    creadoEl: creado("2026-10-03"),
    actualizadoEl: creado("2026-10-03"),
  },
  {
    id: "a-halloween",
    tipo: "idea",
    titulo: "Maquillaje de Halloween en 5 minutos",
    texto: "<p>Con lo que ya tienes en casa.</p>",
    carpetaId: "k-halloween",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-consejos",
    formato: "reel",
    redes: ["instagram"],
    referencias: [{ id: "r6", tipo: "imagen", url: foto(FOTOS.pinceles) }],
    portadaUrl: foto(FOTOS.pinceles),
    fechaClaveId: "halloween",
    creadoEl: creado("2026-09-30"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    id: "a-neceser",
    tipo: "idea",
    titulo: "Mi neceser de viaje",
    texto: "",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-dia",
    formato: "reel",
    redes: ["instagram"],
    referencias: [],
    creadoEl: creado("2026-09-22"),
    actualizadoEl: creado("2026-09-25"),
  },
  {
    id: "a-favoritos-septiembre",
    tipo: "idea",
    titulo: "Favoritos de septiembre",
    texto: "",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-reviews",
    formato: "reel",
    redes: ["instagram"],
    referencias: [],
    creadoEl: creado("2026-09-15"),
    actualizadoEl: creado("2026-09-30"),
  },
  {
    id: "a-retinal",
    tipo: "idea",
    titulo: "Antes y después: 30 días con retinal",
    texto: "<p>Fotos con la misma luz el día 1, el 15 y el 30.</p>",
    carpetaId: "k-probar",
    favorito: false,
    estado: "para-hacer",
    pilarId: "p-reviews",
    formato: "post",
    redes: ["instagram"],
    referencias: [{ id: "r7", tipo: "imagen", url: foto(FOTOS.lumea) }],
    portadaUrl: foto(FOTOS.lumea),
    creadoEl: creado("2026-09-18"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    id: "a-cinco-euros",
    tipo: "idea",
    titulo: "Rutina completa por 5 euros",
    texto: "<p>Lo dejo: no encuentro un protector solar decente por ese precio.</p>",
    favorito: false,
    estado: "descartada",
    pilarId: "p-consejos",
    redes: [],
    referencias: [],
    creadoEl: creado("2026-09-10"),
    actualizadoEl: creado("2026-09-12"),
  },
  {
    id: "a-ganchos",
    tipo: "nota",
    titulo: "Ganchos que me funcionan",
    texto: `<p>Los que mejor han ido este año, para no empezar de cero.</p>${lista([
      "«Esto es lo único que hago por la noche y…»",
      "«Llevo 30 días haciendo esto y mira»",
      "«Nadie te cuenta esto del protector solar»",
      "«Si tienes la piel grasa, no hagas esto»",
      "«El producto de 8 € que ha sustituido a uno de 60 €»",
    ])}`,
    carpetaId: "k-ganchos",
    favorito: true,
    estado: "apuntada",
    redes: [],
    referencias: [],
    creadoEl: creado("2026-06-02"),
    actualizadoEl: creado("2026-10-01"),
  },
  {
    id: "a-mi-estilo",
    tipo: "nota",
    titulo: "Mi estilo: cómo hablo y qué no hago",
    carpetaId: "k-metodo",
    texto: `<h3>Cómo hablo</h3><p>Cercana, sin tecnicismos y diciendo lo que no me gusta.</p><h3>Lo que no hago</h3>${lista(["Prometer resultados que no he visto", "Hablar de productos que no he probado al menos dos semanas", "Publicidad sin marcar"])}`,
    favorito: false,
    estado: "apuntada",
    redes: [],
    referencias: [],
    creadoEl: creado("2026-05-14"),
    actualizadoEl: creado("2026-09-02"),
  },
  {
    id: "a-por-probar",
    tipo: "nota",
    titulo: "Productos por probar",
    texto: lista(["Sérum de niacinamida de farmacia", "Bálsamo limpiador nuevo de Pétalo", "Protector con color de Soleil Paris", "Brocha kabuki que me recomendasteis"]),
    carpetaId: "k-probar",
    favorito: false,
    estado: "apuntada",
    redes: [],
    referencias: [],
    creadoEl: creado("2026-08-20"),
    actualizadoEl: creado("2026-10-04"),
  },
  {
    id: "a-grabacion",
    tipo: "nota",
    titulo: "Antes de grabar",
    carpetaId: "k-metodo",
    texto: lista(["Limpiar la lente", "Luz de la ventana de frente, nunca detrás", "Modo avión", "Batería y espacio en el móvil", "Producto limpio y con la etiqueta hacia cámara"]),
    favorito: false,
    estado: "apuntada",
    redes: [],
    referencias: [],
    creadoEl: creado("2026-04-11"),
    actualizadoEl: creado("2026-08-30"),
  },
]

/** Las notas enlazadas con las ideas que salen de ellas (o que las usan). */
export const demoVinculos: VinculoApunte[] = [
  { desde: "a-ganchos", hasta: "a-colorete-viral" },
  { desde: "a-ganchos", hasta: "a-rutina-noche" },
  { desde: "a-por-probar", hasta: "a-dupes-serums" },
  { desde: "a-por-probar", hasta: "a-retinal" },
  { desde: "a-grabacion", hasta: "a-rutina-noche" },
]

const base = { guion: "", caption: "", publicidad: false }

export const demoContenidos: Contenido[] = [
  {
    ...base,
    id: "c-rutina-noche",
    titulo: "Rutina de noche en 30 segundos",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-07T19:00",
    estado: "editar",
    pilarId: "p-rutinas",
    ideaId: "a-rutina-noche",
    guion: apartados([
      ["Gancho", "«Esto es lo único que hago por la noche y mi piel nunca ha estado mejor.» Cara lavada a cámara, con el bálsamo en la mano."],
      ["Desarrollo", "Bálsamo 30 segundos, agua tibia, sérum de dentro hacia fuera y crema. Nada más. En pantalla: 1. Bálsamo · 2. Sérum · 3. Crema."],
      ["Cierre", "Guárdalo para esta noche."],
      ["Para grabar", "Baño con la luz de la ventana. Plano cenital para el masaje y detalle del sérum. Falta el resultado final."],
    ]),
    caption: "Mi rutina de noche cabe en 30 segundos y mi piel lo agradece.\n\n¿Cuál es el paso que nunca te saltas?\n\n#rutinadenoche #skincare #pielsensible #cuidadofacial",
    portadaUrl: foto(FOTOS.balsamo),
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-01"),
    actualizadoEl: "2026-10-05T18:20:00",
  },
  {
    ...base,
    id: "c-rutina-noche-tiktok",
    titulo: "Rutina de noche en 30 segundos · TikTok",
    formato: "tiktok",
    tipo: "video",
    fecha: "2026-10-08T20:00",
    estado: "editar",
    pilarId: "p-rutinas",
    guion: "<p>El mismo vídeo que el reel, con el texto en pantalla más grande.</p>",
    caption: "La rutina de noche más corta que vas a ver hoy #skincare #rutinadenoche",
    redes: [{ red: "tiktok" }],
    creadoEl: creado("2026-10-02"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    ...base,
    id: "c-cuidar-brochas",
    titulo: "Cómo limpio mis brochas",
    formato: "tiktok",
    tipo: "video",
    fecha: "2026-10-06T21:00",
    estado: "programado",
    pilarId: "p-consejos",
    guion: "<p>«Si no lavas tus brochas, esto es lo que hay en tu cara.» Brochas sucias, jabón y agua tibia, secado en horizontal.</p>",
    caption: "Una vez a la semana, cinco minutos. Tu piel lo nota. #maquillaje #brochas #consejos",
    redes: [{ red: "tiktok" }],
    creadoEl: creado("2026-09-29"),
    actualizadoEl: creado("2026-10-05"),
  },
  {
    ...base,
    id: "c-protector-otono",
    titulo: "3 errores con el protector solar en otoño",
    formato: "post",
    tipo: "carrusel",
    fecha: "2026-10-09T13:00",
    estado: "guion",
    pilarId: "p-consejos",
    guion: apartados([["Portada", "3 errores con el protector solar en otoño"], ["1", "Dejarlo porque está nublado"]]),
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-03"),
    actualizadoEl: creado("2026-10-04"),
  },
  {
    ...base,
    id: "c-colorete-viral",
    titulo: "Probando el truco viral del colorete",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-10T18:00",
    estado: "grabar",
    pilarId: "p-reviews",
    ideaId: "a-colorete-viral",
    guion: apartados([
      ["Gancho", "«Me pongo el colorete antes que la base y esto pasa.» El resultado final, sin explicar."],
      ["Desarrollo", "Colorete en crema solo en un lado, base encima con esponja y comparo los dos lados."],
      ["Cierre", "¿Lo pruebas o te quedas como estás?"],
      ["Para grabar", "Tocador. Colorete en crema, base y esponja. El audio del vídeo original."],
    ]),
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-03"),
    actualizadoEl: creado("2026-10-05"),
  },
  {
    ...base,
    id: "c-preguntas",
    titulo: "Preguntas y respuestas: cómo empecé",
    formato: "story",
    tipo: "video",
    fecha: "2026-10-11",
    estado: "guion",
    pilarId: "p-dia",
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-04"),
    actualizadoEl: creado("2026-10-04"),
  },
  {
    ...base,
    id: "c-neceser",
    titulo: "Mi neceser de viaje",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-13T19:30",
    estado: "listo",
    pilarId: "p-dia",
    ideaId: "a-neceser",
    guion: apartados([
      ["Gancho", "«Me voy cinco días y esto es todo lo que llevo.» El neceser cerrado y la maleta."],
      ["Desarrollo", "Producto a producto, por qué cada uno."],
      ["Cierre", "¿Qué no puede faltar en el tuyo?"],
    ]),
    caption: "Cinco días, un neceser pequeño y cero estrés.\n\n¿Qué no puede faltar en el tuyo?\n\n#neceser #viaje #skincare",
    portadaUrl: foto(FOTOS.crema),
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-09-25"),
    actualizadoEl: creado("2026-10-03"),
  },
  {
    ...base,
    id: "c-piel-grasa",
    titulo: "Skincare para piel grasa en otoño",
    formato: "youtube",
    tipo: "video",
    fecha: "2026-10-16T17:00",
    estado: "guion",
    pilarId: "p-consejos",
    redes: [{ red: "youtube" }],
    creadoEl: creado("2026-10-02"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    ...base,
    id: "c-boda",
    titulo: "Prepárate conmigo: boda de mi prima",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-24T12:00",
    estado: "guion",
    pilarId: "p-dia",
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-05"),
    actualizadoEl: creado("2026-10-05"),
  },
  {
    ...base,
    id: "c-halloween",
    titulo: "Maquillaje de Halloween en 5 minutos",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-29T19:00",
    estado: "guion",
    pilarId: "p-consejos",
    ideaId: "a-halloween",
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-02"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    ...base,
    id: "c-retinal",
    titulo: "Antes y después: 30 días con retinal",
    formato: "post",
    tipo: "carrusel",
    estado: "guion",
    pilarId: "p-reviews",
    ideaId: "a-retinal",
    redes: [{ red: "instagram" }],
    creadoEl: creado("2026-10-02"),
    actualizadoEl: creado("2026-10-02"),
  },
  {
    ...base,
    id: "c-favoritos-septiembre",
    titulo: "Favoritos de septiembre",
    formato: "reel",
    tipo: "video",
    fecha: "2026-10-03T19:00",
    estado: "publicado",
    pilarId: "p-reviews",
    ideaId: "a-favoritos-septiembre",
    guion: "<p>«Cinco productos que no he soltado en todo septiembre.» Los cinco en la mesa y uno a uno.</p>",
    caption: "Mis cinco favoritos del mes. Ninguno es publicidad: los he comprado yo. #favoritos #skincare #maquillaje",
    portadaUrl: foto(FOTOS.glow),
    redes: [{ red: "instagram", url: "https://www.instagram.com/reel/EJEMPLO456/" }],
    creadoEl: creado("2026-09-26"),
    actualizadoEl: creado("2026-10-03"),
  },
]
